@startuml
'https://plantuml.com/class-diagram

interface Toll {
    + void openGate()
    + void closeGate()
}

class Toll1 implements Toll {}
class Toll2 implements Toll {}
class Toll3 implements Toll {}
class Toll4 implements Toll {}

class Vehicle {
}

@enduml